[build]
publish = "cmd/hugothemesitebuilder/build/site/public"
command = "build.sh"

[context.production.environment]
HUGO_VERSION = "0.84.1"

[context.deploy-preview]
command = "build.sh"

[context.deploy-preview.environment]
HUGO_VERSION = "0.84.1"

[context.branch-deploy]
command = "build.sh"

[context.branch-deploy.environment]
HUGO_VERSION = "0.84.1"


